# Generated by Django 5.2.6 on 2025-10-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_word'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word',
        ),
    ]
