# Generated by Django 5.2.6 on 2025-10-25 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_alter_word_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='source_lang',
            field=models.CharField(default='en', help_text='Language of the original word (en/ru)', max_length=10),
        ),
    ]
